### ISSUE TITLE
[2.0.0] secret_manager: missing 1 required positional argument: 'data_crc32'

### ISSUE THREAD

**Issue by guilhem** [scaleway/scaleway-sdk-python#485]
Works on 1.8.0 but fail to get secret when no data_crc32 was specified.

```
unmarshal_AccessSecretVersionResponse
    return AccessSecretVersionResponse(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AccessSecretVersionResponse.__init__() missing 1 required positional argument: 'data_crc32'
```

**Comment by Laure-di** [comment]
Hey!

Good news! The latest release of the scaleway-async package has fixed the issue. To get the update, just run this command:

pip install --upgrade scaleway

Thanks a bunch for your patience and support!
